language: ruby
rvm:
  - "2.1.5"
addons:
	apt_packages:
	- build-essential
	- libsdl2-dev
	- libsdl2-ttf-dev
	- libpango1.0-dev
	- libgl1-mesa-dev
	- libfreeimage-dev
	- libopenal-dev
	- libsndfile-dev
